// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4FFztv3OHHy7mo76ag8cAFKfKj18g7Q',
    appId: '1:178582659060:web:f09349d335be1b6dc7e3a1',
    messagingSenderId: '178582659060',
    projectId: 'mess-app-c35f7',
    authDomain: 'mess-app-c35f7.firebaseapp.com',
    databaseURL: 'https://mess-app-c35f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mess-app-c35f7.firebasestorage.app',
    measurementId: 'G-1H7FWTF3H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu6E8Vhe9U65YEadAyurUG78I2vsMHDj4',
    appId: '1:178582659060:android:1db9256ecf076d10c7e3a1',
    messagingSenderId: '178582659060',
    projectId: 'mess-app-c35f7',
    databaseURL: 'https://mess-app-c35f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mess-app-c35f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4ZFV818DwUrQQyOIrwPqE_43BPQdkvQ',
    appId: '1:178582659060:ios:61ecf9912ac61a26c7e3a1',
    messagingSenderId: '178582659060',
    projectId: 'mess-app-c35f7',
    databaseURL: 'https://mess-app-c35f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mess-app-c35f7.firebasestorage.app',
    iosBundleId: 'com.example.messApp',
  );
}
